const PRODUCTOS = [
    { id: 1, category: "Frutas", price: "$1", stocked: true, name: "Manzana", image: "/imgs/manzana.jpg", description: "Saborea la deliciosa combinación de dulzura y crujencia en cada mordisco de nuestras manzanas." },
    {
        id: 2,
        category: "Frutas",
        price: "$1",
        stocked: true,
        name: "Fruta del dragón",
        image: "/imgs/fruta-del-dragon.jpg",
        description: "¡Descubre el sabor exótico y la textura crujiente de esta fruta tropical!",
    },
    {
        id: 3, category: "Frutas", price: "$2", stocked: false, name: "Maracuyá", image: "/imgs/maracuya.jpg",
        description: "¡Descubre el sabor intenso y la textura crujiente de esta fruta tropical!",
    },
    {
        id: 4, category: "Verduras", price: "$2", stocked: true, name: "Espinaca", image: "/imgs/espinaca.jpg",
        description: "Descubre la frescura y el sabor incomparable de nuestra espinaca de primera calidad.",
    },
    {
        id: 5,
        category: "Verduras",
        price: "$4",
        stocked: false,
        name: "Calabaza",
        image: "/imgs/calabaza.jpg",
        description: "Disfruta de la suavidad y el sabor dulce de nuestra calabaza de alta calidad.",
    },
    {
        id: 6,
        category: "Verduras",
        price: "$1",
        stocked: true,
        name: "Guisantes",
        image: "/imgs/guisantes.jpg",
        description: "Sumérgete en la frescura y el sabor delicado de nuestros guisantes de alta calidad. ",
    },
    {
        id: 7,
        category: "Electrodomésticos",
        price: "$250",
        stocked: true,
        name: "Heladera",
        image: "/imgs/heladera.jpg",
        description: "Descubre la combinación perfecta de estilo y funcionalidad con nuestra heladera de última generación.",
    },
    {
        id: 8,
        category: "Electrodomésticos",
        price: "$150",
        stocked: true,
        name: "Microondas",
        image: "/imgs/microondas.png",
        description: "Mejora tu experiencia en la cocina con nuestro microondas de última generación.",
    },
    {
        id: 9,
        category: "Electrodomésticos",
        price: "$150",
        stocked: true,
        name: "Horno",
        image: "/imgs/horno.jpg",
        description: "Transforma tu cocina con nuestro horno de última generación, diseñado para ofrecerte rendimiento, precisión y estilo.",
    },
    {
        id: 10,
        category: "Ropa",
        price: "$150",
        stocked: true,
        name: "Buzo Adidas",
        image: "/imgs/buzo-adidas.jpeg",
        description: "Lleva tu estilo al siguiente nivel con el buzo Adidas, diseñado para ofrecerte la máxima comodidad y un look deportivo inigualable.",
    },
    {
        id: 11,
        category: "Ropa",
        price: "$150",
        stocked: false,
        name: "Pantalón Nike",
        image: "/imgs/pantalon-nike.png",
        description: "Descubre el pantalón Nike, diseñado para ofrecerte el máximo confort y rendimiento en cada actividad.",
    },
    {
        id: 12, category: "Ropa", price: "$150", stocked: true, name: "Medias", image: "/imgs/medias.jpg",
        description: "Eleva tu rendimiento y comodidad diaria con nuestras medias, diseñadas para ofrecerte soporte, durabilidad y un ajuste perfecto.",
    },
    {
        id: 13, category: "Dulces", price: "$1", stocked: false, name: "Chupetín", image: "/imgs/chupetines.jpg",
        description: "Disfruta del sabor y la diversión con nuestros chupetines, perfectos para cualquier ocasión. Con una amplia variedad de sabores y colores vibrantes, nuestros chupetines son el dulce ideal para alegrar tu día.",
    },
    {
        id: 14, category: "Dulces", price: "$2", stocked: true, name: "Alfajor", image: "/imgs/alfajores.jpg",
        description: "Descubre la exquisitez de nuestros alfajores, una delicia tradicional que combina sabores y texturas irresistibles.",
    },
    {
        id: 15,
        category: "Dulces",
        price: "$0,50",
        stocked: false,
        name: "Chicles",
        image: "/imgs/chicles.jpg",
        description: "Experimenta la explosión de sabor y frescura con nuestros chicles de alta calidad.",
    },
    {
        id: 16,
        category: "Salado",
        price: "$1",
        stocked: true,
        name: "Papas fritas",
        image: "/imgs/papas-fritas.jpg",
        description: "Disfruta del sabor y la textura inigualables de nuestras papas fritas.",
    },
    {
        id: 17, category: "Salado", price: "$2", stocked: false, name: "Chizitos", image: "/imgs/chizitos.jpeg",
        description: "Sumérgete en la diversión y el sabor con nuestros chisitos, el snack perfecto para cualquier ocasión. ",
    },
    {
        id: 18,
        category: "Salado",
        price: "$1,50",
        stocked: true,
        name: "Palitos salados",
        image: "/imgs/palitos-salados.webp",
        description: "Descubre la combinación perfecta de sabor salado y textura crujiente con nuestros palitos salados.",
    },
];

export default PRODUCTOS