const PRODUCTOS = [
    { id: 1, category: "Frutas", price: "$1", stocked: true, name: "Manzana" },
    {
        id: 2,
        category: "Frutas",
        price: "$1",
        stocked: true,
        name: "Fruta del dragón",
    },
    { id: 3, category: "Frutas", price: "$2", stocked: false, name: "Maracuyá" },
    { id: 4, category: "Verduras", price: "$2", stocked: true, name: "Espinaca" },
    {
        id: 5,
        category: "Verduras",
        price: "$4",
        stocked: false,
        name: "Calabaza",
    },
    {
        id: 6,
        category: "Verduras",
        price: "$1",
        stocked: true,
        name: "Guisantes",
    },
    {
        id: 7,
        category: "Electrodomesticos",
        price: "$250",
        stocked: true,
        name: "Heladera",
    },
    {
        id: 8,
        category: "Electrodomesticos",
        price: "$150",
        stocked: true,
        name: "Microondas",
    },
    {
        id: 9,
        category: "Electrodomesticos",
        price: "$150",
        stocked: true,
        name: "Horno",
    },
    {
        id: 10,
        category: "Ropa",
        price: "$150",
        stocked: true,
        name: "Buzo Adidas",
    },
    {
        id: 11,
        category: "Ropa",
        price: "$150",
        stocked: false,
        name: "Pantalón Nike",
    },
    { id: 12, category: "Ropa", price: "$150", stocked: true, name: "Medias" },
    { id: 13, category: "Dulces", price: "$1", stocked: false, name: "Chupetín" },
    { id: 14, category: "Dulces", price: "$2", stocked: true, name: "Alfajor" },
    {
        id: 15,
        category: "Dulces",
        price: "$0,50",
        stocked: false,
        name: "Chicles",
    },
    {
        id: 16,
        category: "Salado",
        price: "$1",
        stocked: true,
        name: "Papas fritas",
    },
    { id: 17, category: "Salado", price: "$2", stocked: false, name: "Chisitos" },
    {
        id: 18,
        category: "Salado",
        price: "$1,50",
        stocked: true,
        name: "Palitos salados",
    },
];

export default PRODUCTOS